version: '3.8'

services:
  dan-web-server:
    build: .
    container_name: dan-web-server
    environment:
        DATABASE_HOSTNAME: 'postgres'
        REDIS_URL: 'redis'
        PORT: 8080
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.2-bullseye
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'mysecretpassword'
        POSTGRES_USER: 'postgres'

  redis:
    image: 'redis:alpine'
    container_name: redis